# Generated by Django 4.0.5 on 2022-07-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('result', models.CharField(max_length=1000)),
                ('media', models.CharField(max_length=1000)),
                ('media_result', models.CharField(max_length=1000)),
            ],
        ),
    ]
