# Generated by Django 4.0.5 on 2022-08-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_organization', models.CharField(max_length=1000)),
                ('type_of_organization', models.CharField(choices=[('GO', 'GOVERMENT ORGANIZATION'), ('NGO', 'NON-GOVERNMENT ORGANIZATION'), ('OTH', 'PRIVATE COMPANY')], max_length=1000)),
                ('admin_email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('admin_whatsapp_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('keywords', models.CharField(max_length=1000)),
            ],
        ),
    ]
